droidtvsettings:fix crash[1/1]
PD# 166682

fix droidtvsettings crash caused by
java.lang.SecurityException: Permission Denial:
getCurrentUser() from pid=6756, uid=10070
requires android.permission.INTERACT_ACROSS_USERS

change-Id: Idbc53b5bb199f308a27b73e90b67db7335a5d360